name: SlimePads
version: ${project.version}
main: me.buryings.slimepads.SlimePads
authors: [ Buryings ]
description: Turn slime blocks into launch pads!
commands:
  spreload:
    description: Reloads plugin config
